### ISSUE TITLE
Proposal: rename the nodejs/iojs-nl WG to nodejs/nodejs-nl

### ISSUE THREAD

**Issue by srl295** [iojs/iojs-nl#16]
Dear members of the io.js Dutch WG `iojs-nl`

It is proposed to rename this repo to:

   [nodejs/nodejs-nl](https://github.com/nodejs/nodejs-nl/)

As part of the io.js and node.js convergence, node.js releases are now based on the codebase and user base of the converged node.js and io.js communities. A number of the resources and repositories have already been renamed.
In the absence of objections or other discussion, this rename will occur on or after [Oct 28, 2015](http://time.is/1200AM_28_Oct_2015_in_GMT?iojs-rename)

However, active language working groups should take ownership of this issue and discuss/dispose of it according to their own processes.

For more information or to discuss the overall issue, please see and comment on https://github.com/nodejs/node/issues/2525

This statement was authorized by the Node.js TSC

Cc: @nodejs/iojs-nl

**Comment by AdriVanHoudt** [comment]
done

**Comment by AdriVanHoudt** [comment]
ref https://github.com/nodejs/nodejs-nl/commit/143be503833786a3feccdbeae884e0368e441c88
