### ISSUE TITLE
Translate week of Feb 6 2015 blog post

### ISSUE THREAD

**Issue by timdp** [iojs/iojs-nl#3]
https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4

Starting now, unless @yoshuawuyts is already doing it.

**Comment by yoshuawuyts** [comment]
@timdp go for it! :D

**Comment by timdp** [comment]
Just finished an initial draft! Do you have Google Drive on your email address so I can share it?

**Comment by yoshuawuyts** [comment]
@timdp aye! Though a GH gist will also work for me (open communication, etc.) ^^

**Comment by timdp** [comment]
Great idea! [Here's the gist.](https://gist.github.com/timdp/a6a25f2b7d41d116e6c8)

I'm still fiddling with the tone. Do feel free to change every single word.

**Comment by yoshuawuyts** [comment]
@timdp LGTM! :tada: Only change I'd suggest is `werkgroep website` -> `website werkgroep`. Neat job dude!

**Comment by timdp** [comment]
Thanks!

The reason why I switched those words around is because "websitewerkgroep" would need to be one long, ugly word. Maybe we should add a hyphen then?

Where should we publish this? I've never written anything on Medium, but since the original is there, I guess it makes a lot of sense for us as well.

**Comment by timdp** [comment]
I've created a Medium account (linked to our Twitter account) and published the translated post at https://medium.com/@iojsnl/io-js-week-van-6-februari-2015-d6907c8054fd

**Comment by yoshuawuyts** [comment]
@timdp wooh! Nice job! :tada: Also like the medium part, guess it makes sense to have it there.

**re websitewerkgroep:** I think a hyphen looks good in there ^^

**Comment by timdp** [comment]
I made it one word on Medium, but we can still edit the post if you like. The rule basically says that it should be one word unless there's a good reason not to make it one. I'm not sure if "it looks ugly" will hold up though. :)

**Comment by yoshuawuyts** [comment]
An artistic twirl to linguistics that improves readability is a welcome change imo. That said, it's very minor. Feel free to leave it however you see fit.

**Comment by yoshuawuyts** [comment]
Tweet sent! https://twitter.com/iojs_nl/status/564214323716030464 Not sure how we want to sync these events in the future. iojs_official newsletter releases happen every friday. Do we want to release asap after that, or on a planned day?

**Comment by timdp** [comment]
Not sure. As soon as possible, I would say. In the blog post, I snuck in "weekly" rather than "every Friday".

**Comment by yoshuawuyts** [comment]
@timdp :clap: sounds good.

**Comment by AdriVanHoudt** [comment]
How late do they publish? If they publish in the morning it is possible to translate that day but idd I would go with just weekly ;).

**Comment by timdp** [comment]
There are only three of us, so I'd say it's best effort for now. :)

Closing this issue so we don't go off-topic too much.

**Comment by AdriVanHoudt** [comment]
:+1:
