### ISSUE TITLE
Changelog translation

### ISSUE THREAD

**Issue by AdriVanHoudt** [iojs/iojs-nl#7]
I saw that io.js_cn translated the changelog which doesn't seem like a bad idea. But for their, and our own sanity, they translated only from 1.0.0 up.

https://github.com/iojs/iojs-cn/blob/master/CHANGELOG.md

original: https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md

**Comment by yoshuawuyts** [comment]
Oh yeah, that's not bad. Not sure how many people would like to have this, but I don't see why we shouldn't test it out. @AdriVanHoudt would you like to give it a go?

**Comment by AdriVanHoudt** [comment]
Me neither :P and I can, but I'm just starting my work day so I'll see when I have time

**Comment by AdriVanHoudt** [comment]
@timdp how would I prefix the changelog, if at all? With the current date or the date of the changelog or...?

**Comment by timdp** [comment]
How do you mean? Would you create a new partial changelog per version rather than prepending to CHANGELOG.md every time?

**Comment by AdriVanHoudt** [comment]
No but should we prefix the changelog file as you suggested?
- 201-02-10_CHANGELOG.md (now)
- 2015-02-03_CHANGELOG.md (last update of changelog)
- CHANGELOG.md (no prefix)

**Comment by timdp** [comment]
I would only do that for the blog posts, personally.

**Comment by AdriVanHoudt** [comment]
yeah I don't like the idea of prefixing the changelog either. We'll only prefix the blogs then.

**Comment by AdriVanHoudt** [comment]
See #10

**Comment by yoshuawuyts** [comment]
`<thought_dump>`

I'm having increasing reservations on how useful this will turn out to be. Given how many technical terms remain in English + commit messages are also in English it feels like it'd be easier to just read the original document.

I think we should also think about who we're targeting here. I believe the majority of developers in Dutch speaking countries are well versed in English, which kind of sets us apart from other i18n communities where the language spoken is also the language used to program in. Following that line of thought we'd end up having an i18n effort focused on non-programmers, to whom a `CHANGELOG` is much less relevant than the weekly overviews which outlines the grand details.

`</thought_dump>`

 How do you guys feel about this?

**Comment by AdriVanHoudt** [comment]
@yoshuawuyts hmm I somewhat agree although we can do a distilled dutch changelog with all the major stuff in it (see comment in PR)

**Comment by timdp** [comment]
I agree, Yoshua. Our resources are limited, so we should focus on what's important. To me, that's localizing 1) the blog (because it provides a bird's-eye view), 2) io.js itself, and 3) documentation. No word on 2) and 3) yet, but I assume they're coming.

**Comment by yoshuawuyts** [comment]
@timdp also https://github.com/iojs/iojs-nl/issues/13 (just created ^^)

**Comment by AdriVanHoudt** [comment]
closed the PR for now so also this issue
