### ISSUE TITLE
io.js and a node.js foundation

### ISSUE THREAD

**Issue by yoshuawuyts** [iojs/iojs-nl#8]
Anyone up for translating? If there are no takers I'll give it a go. https://medium.com/@iojs/io-js-and-a-node-js-foundation-4e14699fb7be

**Comment by AdriVanHoudt** [comment]
damn you beat me to it :P and you can take it unless @timdp wants it, I'm doing the changelog atm

**Comment by timdp** [comment]
All yours. :)

**Comment by AdriVanHoudt** [comment]
@yoshuawuyts can you post it on medium?

**Comment by yoshuawuyts** [comment]
@AdriVanHoudt currently not in a position to do so, can you do it?

**Comment by AdriVanHoudt** [comment]
@yoshuawuyts I don't have the login of the iojs-nl Medium account

**Comment by AdriVanHoudt** [comment]
@yoshuawuyts if you have the login and you want to share it you can mail it to me at adri.van.houdt@gmail.com

**Comment by yoshuawuyts** [comment]
@AdriVanHoudt done

**Comment by AdriVanHoudt** [comment]
@yoshuawuyts thanks, I'm posting it right now, any suggestions for a tweet?

**Comment by AdriVanHoudt** [comment]
done https://twitter.com/iojs_nl/status/565540516813881344
